### PR TITLE
Migrate from ErikWDev/sokol-rust to floooh/sokol-rust

### PR DESCRIPTION
**Pull request by EriKWDev**
## Initial rust bindings for sokol headers
Checkout the issue on floooh/sokol https://github.com/floooh/sokol/issues/802 for decisions taken regarding the rust bindings.

I have tested all examples on Linux with X11, Windows 10 and Macos on an M1 macbook pro. It also compiles using emscripten tested in firefox.  There is also a Github workflow setup to compile all examples on Ubuntu, Windows and Mac x86.

## Integrating the bindings
`gen_rust.py` is setup the same way as the other generators. One thing to note is that I added support for the imgui headers as well for the rust bindings so those need to be added to the tasks in `gen_all.py`:
```python
tasks = [
    # ...
    [ '../util/sokol_imgui.h',     'simgui_',   ['sg_', 'sapp_'] ],
    [ '../util/sokol_gfx_imgui.h', 'sg_imgui_', ['sg_'] ],
]
```
## Problem with sokol_gfx_imgui.h
There was a problem in `gen_ir.py` for the imgui headers since `sokol_gfx_imgui.h` depends on `sokol_gfx.h` which uses the prefix `sg_` which is same for the `sg_imgui_`. This causes all types and functions that start with `sg_imgui` to be marked as `is_dep` since the function thinks it belongs to `sg_` 

```python
# gen_ir.py

def is_dep_decl(decl, dep_prefixes):
    # FIXME: sg_imgui_ declarations start with sg_imgui_, but also depend
    # on sg_ functions. I beleive this accidentally marks all sg_imgui_ functions as
    # is_dep even if they're not...

    for prefix in dep_prefixes:
        if is_api_decl(decl, prefix):
            return True
    return False
```

So I made a workaround in my `gen_rust.py`
```python
# .. in gen_module():
        #    HACK: gen_ir.py accidentally marks all sg_imgui_ declarations as is_dep since sg_imgui
        #          depends on functons from gfx marked with sg_.. Fix gen_ir.py to remove this hack
        dep_hack = False
        if module == "gfx_imgui":
            dep_hack = "name" in decl and decl["name"].startswith("sg_imgui_")

        if not decl["is_dep"] or dep_hack:

```

## Shaders
I will make a separate PR to sokol-tools integrating the rust shader generation code, but it is currently included here as well.
https://github.com/floooh/sokol-tools/pull/84

### CODE REVIEW

**Comment by EriKWDev** [comment]
Also, I of course release this to the sokol project and you are free to give it any FOSS license of your choosing that is similar to zlib/MIT. Attribution is appreciated

**Comment by floooh** [comment]
As for the license, feel free to add an MIT or zlib LICENSE.txt to the sokol-rust repo with your name in it (but please no license that is more restrictive than MIT or zlib). I actually have been fairly inconsistent with the bindings licenses (in sokol-zig and sokol-odin I don't have a LICENSE.txt at all, while in sokol-nim there's an MIT license, while the sokol headers had been switched to the more liberal zlib license a while ago (which doesn't require attribution)). In general I try to track contributors via their git commits (sometimes this mysteriously breaks though when there's something wrong with the PR).

**Comment by floooh** [comment]
> Problem with sokol_gfx_imgui.h

...ah hmm, I didn't notice this prefix problem so far because sokol_gfx_imgui.h isn't part of the other bindings so far... I'll try to keep it in mind (e.g. at some point the prefix should be changed to sgimgui_)

**Comment by floooh** [comment]
Ok merged, I'll tinker around a bit with this in the next few days to get familiar with the bindings and build workflow.

Do you also have a PR for the bindings generation script to put into sokol? Or did I just not see that? :)

**Pull request merged**
